export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_COUNTER = 'ADD_COUNTER';
export const SUBTRACT = 'SUBTRACT';

export const CHANGE_COLOR = 'CHANGE_COLOR';

export const FETCH_COUNTER_REQUEST = 'FETCH_COUNTER_REQUEST';
export const FETCH_COUNTER_SUCCESS = 'FETCH_COUNTER_SUCCESS';
export const FETCH_COUNTER_ERROR = 'FETCH_COUNTER_ERROR';

export const TASKS_REQUEST = "TASKS_REQUEST";
export const GET_TASKS = "GET_TASKS";
export const ERROR_TASKS = "ERROR_TASKS";

export const REMOVE_TASK_API = "REMOVE_TASK_API"

export const CREATE_TASK = "CREATE_TASK";

export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";

export const UPDATE_TASK = "UPDATE_TASK";
export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";